# Generated by Django 4.1 on 2022-09-01 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('child1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Child3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=256)),
                ('lastName', models.CharField(max_length=256)),
                ('cricketTeam', models.CharField(max_length=256)),
                ('role', models.CharField(max_length=256)),
            ],
        ),
    ]
